import { Position } from '../../positions/position';
import { Player } from '../player';
import { Team } from '../../teams/team';

export const ROOKIES_2019 = [
    Player.newBuilder().setPosition(Position.C).setName('Cesar Ruiz').setTeam(Team.NOR).setAge(21).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.C).setName('Dustin Woodard').setTeam(Team.NWE).setAge(22).setSchool('Memphis').build(),
    Player.newBuilder().setPosition(Position.C).setName('Jake Hanson').setTeam(Team.GNB).setAge(23).setSchool('Oregon').build(),
    Player.newBuilder().setPosition(Position.C).setName('Keith Ismael').setTeam(Team.WAS).setAge(22).setSchool('San Diego St.').build(),
    Player.newBuilder().setPosition(Position.C).setName('Lloyd Cushenberry III').setTeam(Team.DEN).setAge(22).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.C).setName('Matt Hennessy').setTeam(Team.ATL).setAge(22).setSchool('Temple').build(),
    Player.newBuilder().setPosition(Position.C).setName('Nick Harris').setTeam(Team.CLE).setAge(21).setSchool('Washington').build(),
    Player.newBuilder().setPosition(Position.C).setName('Tyler Biadasz').setTeam(Team.DAL).setAge(22).setSchool('Wisconsin').build(),
    Player.newBuilder().setPosition(Position.CB).setName('AJ Terrell').setTeam(Team.ATL).setAge(21).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Amik Robertson').setTeam(Team.LVR).setAge(22).setSchool('Louisiana Tech').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Bryce Hall').setTeam(Team.NYJ).setAge(23).setSchool('Virginia').build(),
    Player.newBuilder().setPosition(Position.CB).setName('C.J. Henderson').setTeam(Team.JAX).setAge(21).setSchool('Florida').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Cameron Dantzler').setTeam(Team.MIN).setAge(22).setSchool('Mississippi St.').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Chris Claybrooks').setTeam(Team.JAX).setAge(23).setSchool('Memphis').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Chris Williamson').setTeam(Team.NYG).setAge(23).setSchool('Minnesota').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Damon Arnette').setTeam(Team.LVR).setAge(24).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Dane Jackson').setTeam(Team.BUF).setAge(23).setSchool('Pittsburgh').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Darnay Holmes').setTeam(Team.NYG).setAge(22).setSchool('UCLA').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Harrison Hand').setTeam(Team.MIN).setAge(21).setSchool('Temple').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Isaiah Rodgers').setTeam(Team.IND).setAge(22).setSchool('Massachusetts').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Jaylon Johnson').setTeam(Team.CHI).setAge(21).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Jeff Gladney').setTeam(Team.MIN).setAge(23).setSchool('TCU').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Jeff Okudah').setTeam(Team.DET).setAge(21).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.CB).setName('John Reid').setTeam(Team.HOU).setAge(24).setSchool('Penn St.').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Josiah Scott').setTeam(Team.JAX).setAge(21).setSchool('Michigan St.').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Kindle Vildor').setTeam(Team.CHI).setAge(22).setSchool('Georgia Southern').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Kristian Fulton').setTeam(Team.TEN).setAge(22).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Michael Ojemudia').setTeam(Team.DEN).setAge(22).setSchool('Iowa').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Noah Igbinoghene').setTeam(Team.MIA).setAge(20).setSchool('Auburn').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Reggie Robinson II').setTeam(Team.DAL).setAge(23).setSchool('Tulsa').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Stantley Thomas-Oliver').setTeam(Team.CAR).setAge(22).setSchool('Florida International').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Thakarius Keyes').setTeam(Team.KAN).setAge(22).setSchool('Tulane').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Trevon Diggs').setTeam(Team.DAL).setAge(21).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.CB).setName('Troy Pride Jr.').setTeam(Team.CAR).setAge(22).setSchool('Notre Dame').build(),
    Player.newBuilder().setPosition(Position.DE).setName('A.J. Epenesa').setTeam(Team.BUF).setAge(21).setSchool('Iowa').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Alton Robinson').setTeam(Team.SEA).setAge(22).setSchool('Syracuse').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Bradlee Anae').setTeam(Team.DAL).setAge(21).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Casey Toohill').setTeam(Team.PHI).setAge(24).setSchool('Stanford').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Chase Young').setTeam(Team.WAS).setAge(21).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Curtis Weaver').setTeam(Team.MIA).setAge(22).setSchool('Boise St.').build(),
    Player.newBuilder().setPosition(Position.DE).setName('D.J. Wonnum').setTeam(Team.MIN).setAge(22).setSchool('South Carolina').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Darrell Taylor').setTeam(Team.SEA).setAge(23).setSchool('Tennessee').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Jabari Zuniga').setTeam(Team.NYJ).setAge(23).setSchool('Florida').build(),
    Player.newBuilder().setPosition(Position.DE).setName('James Smith-Williams').setTeam(Team.WAS).setAge(23).setSchool('North Carolina St.').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Jason Strowbridge').setTeam(Team.MIA).setAge(23).setSchool('North Carolina').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Jonathan Garvin').setTeam(Team.GNB).setAge(21).setSchool('Miami (FL)').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Jonathan Greenard').setTeam(Team.HOU).setAge(23).setSchool('Florida').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Julian Okwara').setTeam(Team.DET).setAge(22).setSchool('Notre Dame').build(),
    Player.newBuilder().setPosition(Position.DE).setName("K'Lavon Chaisson").setTeam(Team.JAX).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Kenny Willekes').setTeam(Team.MIN).setAge(23).setSchool('Michigan St.').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Khalid Kareem').setTeam(Team.CIN).setAge(22).setSchool('Notre Dame').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Marlon Davidson').setTeam(Team.ATL).setAge(22).setSchool('Auburn').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Michael Danna').setTeam(Team.KAN).setAge(22).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Trevis Gipson').setTeam(Team.CHI).setAge(23).setSchool('Tulsa').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Yetur Gross-Matos').setTeam(Team.CAR).setAge(22).setSchool('Penn St.').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Bravvion Roy').setTeam(Team.CAR).setAge(23).setSchool('Baylor').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Broderick Washington Jr.').setTeam(Team.BAL).setAge(23).setSchool('Texas Tech').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Carlos Davis').setTeam(Team.PIT).setAge(24).setSchool('Nebraska').build(),
    Player.newBuilder().setPosition(Position.DT).setName('DaVon Hamilton').setTeam(Team.JAX).setAge(23).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Derrick Brown').setTeam(Team.CAR).setAge(22).setSchool('Auburn').build(),
    Player.newBuilder().setPosition(Position.DT).setName('James Lynch').setTeam(Team.MIN).setAge(21).setSchool('Baylor').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Jashon Cornell').setTeam(Team.DET).setAge(23).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Javon Kinlaw').setTeam(Team.SFO).setAge(22).setSchool('South Carolina').build(),
    Player.newBuilder().setPosition(Position.DT).setName('John Penisini').setTeam(Team.DET).setAge(23).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Jordan Elliott').setTeam(Team.CLE).setAge(22).setSchool('Texas').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Justin Madubuike').setTeam(Team.BAL).setAge(22).setSchool('Texas A&M').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Khalil Davis').setTeam(Team.TAM).setAge(24).setSchool('Nebraska').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Larrell Murchison').setTeam(Team.TEN).setAge(23).setSchool('North Carolina St.').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Leki Fotu').setTeam(Team.ARI).setAge(22).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.DT).setName('McTelvin Agim').setTeam(Team.DEN).setAge(22).setSchool('Arkansas').build(),
    Player.newBuilder().setPosition(Position.DE).setName('Neville Gallimore').setTeam(Team.DAL).setAge(23).setSchool('Oklahoma').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Raekwon Davis').setTeam(Team.MIA).setAge(23).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Rashard Lawrence').setTeam(Team.ARI).setAge(22).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Robert Windsor').setTeam(Team.IND).setAge(23).setSchool('Penn St.').build(),
    Player.newBuilder().setPosition(Position.DT).setName('Ross Blacklock').setTeam(Team.HOU).setAge(22).setSchool('TCU').build(),
    Player.newBuilder().setPosition(Position.G).setName('Ben Bartch').setTeam(Team.JAX).setAge(22).setSchool("Saint John's").build(),
    Player.newBuilder().setPosition(Position.G).setName('Ben Bredeson').setTeam(Team.BAL).setAge(22).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.G).setName('Damien Lewis').setTeam(Team.SEA).setAge(23).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.G).setName('Danny Pinter').setTeam(Team.IND).setAge(24).setSchool('Ball St.').build(),
    Player.newBuilder().setPosition(Position.G).setName('Jack Driscoll').setTeam(Team.PHI).setAge(23).setSchool('Auburn').build(),
    Player.newBuilder().setPosition(Position.G).setName('John Simpson').setTeam(Team.LVR).setAge(23).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.G).setName('Jonah Jackson').setTeam(Team.DET).setAge(23).setSchool('Rutgers').build(),
    Player.newBuilder().setPosition(Position.G).setName('Kevin Dotson').setTeam(Team.PIT).setAge(23).setSchool('Louisiana').build(),
    Player.newBuilder().setPosition(Position.G).setName('Kyle Hinton').setTeam(Team.MIN).setAge(22).setSchool('0').build(),
    Player.newBuilder().setPosition(Position.G).setName('Lachavious Simmons').setTeam(Team.CHI).setAge(23).setSchool('').build(),
    Player.newBuilder().setPosition(Position.G).setName('Logan Stenberg').setTeam(Team.DET).setAge(23).setSchool('Kentucky').build(),
    Player.newBuilder().setPosition(Position.G).setName('Michael Onwenu').setTeam(Team.NWE).setAge(22).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.G).setName('Netane Muti').setTeam(Team.DEN).setAge(21).setSchool('Fresno St.').build(),
    Player.newBuilder().setPosition(Position.G).setName('Robert Hunt').setTeam(Team.MIA).setAge(24).setSchool('Louisiana').build(),
    Player.newBuilder().setPosition(Position.G).setName('Shane Lemieux').setTeam(Team.NYG).setAge(23).setSchool('Oregon').build(),
    Player.newBuilder().setPosition(Position.G).setName('Solomon Kindley').setTeam(Team.MIA).setAge(23).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.G).setName('Tremayne Anchrum').setTeam(Team.LAR).setAge(22).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.K).setName('Justin Rohrwasser').setTeam(Team.NWE).setAge(23).setSchool('Marshall').build(),
    Player.newBuilder().setPosition(Position.K).setName('Sam Sloman').setTeam(Team.LAR).setAge(22).setSchool('Miami (OH)').build(),
    Player.newBuilder().setPosition(Position.K).setName('Tyler Bass').setTeam(Team.BUF).setAge(23).setSchool('Georgia Southern').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Akeem Davis-Gaither').setTeam(Team.CIN).setAge(22).setSchool('Appalachian St.').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Alex Highsmith').setTeam(Team.PIT).setAge(23).setSchool('Charlotte').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Anfernee Jennings').setTeam(Team.NWE).setAge(23).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Cam Brown').setTeam(Team.NYG).setAge(22).setSchool('Penn St.').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Carter Coughlin').setTeam(Team.NYG).setAge(23).setSchool('Minnesota').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Cassh Maluia').setTeam(Team.NWE).setAge(21).setSchool('Wyoming').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Chapelle Russell').setTeam(Team.TAM).setAge(23).setSchool('Temple').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Clay Johnston').setTeam(Team.LAR).setAge(24).setSchool('Baylor').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Davion Taylor').setTeam(Team.PHI).setAge(22).setSchool('Colorado').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Derrek Tuszka').setTeam(Team.DEN).setAge(24).setSchool('North').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Evan Weaver').setTeam(Team.ARI).setAge(22).setSchool('California').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Isaiah Simmons').setTeam(Team.ARI).setAge(22).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Jacob Phillips').setTeam(Team.CLE).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Jordan Glasgow').setTeam(Team.IND).setAge(24).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Jordyn Brooks').setTeam(Team.SEA).setAge(22).setSchool('Texas Tech').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Josh Uche').setTeam(Team.NWE).setAge(21).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Justin Strnad').setTeam(Team.DEN).setAge(24).setSchool('Wake Forest').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Kamal Martin').setTeam(Team.GNB).setAge(22).setSchool('Minnesota').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Kenneth Murray').setTeam(Team.LAC).setAge(21).setSchool('Oklahoma').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Khaleke Hudson').setTeam(Team.WAS).setAge(22).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Logan Wilson').setTeam(Team.CIN).setAge(24).setSchool('Wyoming').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Malik Harrison').setTeam(Team.BAL).setAge(22).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Markus Bailey').setTeam(Team.CIN).setAge(23).setSchool('Purdue').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Mykal Walker').setTeam(Team.ATL).setAge(23).setSchool('Fresno St.').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Patrick Queen').setTeam(Team.BAL).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Shaquille Quarterman').setTeam(Team.JAX).setAge(22).setSchool('Miami (FL)').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Shaun Bradley').setTeam(Team.PHI).setAge(23).setSchool('Temple').build(),
    Player.newBuilder().setPosition(Position.LB).setName('T.J. Brunson').setTeam(Team.NYG).setAge(22).setSchool('South Carolina').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Tae Crowder').setTeam(Team.NYG).setAge(23).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Terrell Lewis').setTeam(Team.LAR).setAge(22).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Troy Dye').setTeam(Team.MIN).setAge(23).setSchool('Oregon').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Willie Gay Jr.').setTeam(Team.KAN).setAge(22).setSchool('Mississippi St.').build(),
    Player.newBuilder().setPosition(Position.LB).setName('Zack Baun').setTeam(Team.NOR).setAge(23).setSchool('Wisconsin').build(),
    Player.newBuilder().setPosition(Position.LS).setName('Blake Ferguson').setTeam(Team.MIA).setAge(23).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.P).setName('Braden Mann').setTeam(Team.NYJ).setAge(22).setSchool('Texas A&M').build(),
    Player.newBuilder().setPosition(Position.P).setName('Sterling Hofrichter').setTeam(Team.ATL).setAge(23).setSchool('Syracuse').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Ben DiNucci').setTeam(Team.DAL).setAge(23).setSchool('James Madison').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Cole McDonald').setTeam(Team.TEN).setSchool('Hawaii').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Jacob Eason').setTeam(Team.IND).setAge(22).setSchool('Washington').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Jake Fromm').setTeam(Team.BUF).setAge(22).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Jake Luton').setTeam(Team.JAX).setAge(24).setSchool('Oregon St.').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Jalen Hurts').setTeam(Team.PHI).setAge(22).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.QB).setName('James Morgan').setTeam(Team.NYJ).setAge(23).setSchool('Florida International').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Joe Burrow').setTeam(Team.CIN).setAge(23).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Jordan Love').setTeam(Team.GNB).setAge(21).setSchool('Utah St.').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Justin Herbert').setTeam(Team.LAC).setAge(22).setSchool('Oregon').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Nate Stanley').setTeam(Team.MIN).setAge(23).setSchool('Iowa').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Tommy Stevens').setTeam(Team.NOR).setAge(23).setSchool('Mississippi St.').build(),
    Player.newBuilder().setPosition(Position.QB).setName('Tua Tagovailoa').setTeam(Team.MIA).setAge(22).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.RB).setName('AJ Dillon').setTeam(Team.GNB).setAge(22).setSchool('Boston Col.').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Anthony McFarland Jr.').setTeam(Team.PIT).setAge(21).setSchool('Maryland').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Antonio Gibson').setTeam(Team.WAS).setAge(22).setSchool('Memphis').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Cam Akers').setTeam(Team.LAR).setAge(21).setSchool('Florida St.').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Clyde Edwards-Helaire').setTeam(Team.KAN).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.RB).setName("D'Andre Swift").setTeam(Team.DET).setAge(21).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Darrynton Evans').setTeam(Team.TEN).setAge(22).setSchool('Appalachian St.').build(),
    Player.newBuilder().setPosition(Position.RB).setName('DeeJay Dallas').setTeam(Team.SEA).setAge(21).setSchool('Miami (FL)').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Eno Benjamin').setTeam(Team.ARI).setAge(21).setSchool('Arizona St.').build(),
    Player.newBuilder().setPosition(Position.RB).setName('J.K. Dobbins').setTeam(Team.BAL).setAge(21).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Jason Huntley').setTeam(Team.DET).setAge(22).setSchool('New Mexico St.').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Jonathan Taylor').setTeam(Team.IND).setAge(21).setSchool('Wisconsin').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Joshua Kelley').setTeam(Team.LAC).setAge(22).setSchool('UCLA').build(),
    Player.newBuilder().setPosition(Position.RB).setName("Ke'Shawn Vaughn").setTeam(Team.TAM).setAge(23).setSchool('Illinois').build(),
    Player.newBuilder().setPosition(Position.RB).setName("La'Mical Perine").setTeam(Team.NYJ).setAge(22).setSchool('Florida').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Malcolm Perry').setTeam(Team.MIA).setAge(23).setSchool('Navy').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Raymond Calais').setTeam(Team.TAM).setAge(22).setSchool('Louisiana').build(),
    Player.newBuilder().setPosition(Position.RB).setName('Zack Moss').setTeam(Team.BUF).setAge(22).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.S).setName('Alohi Gilman').setTeam(Team.LAC).setAge(22).setSchool('Notre Dame').build(),
    Player.newBuilder().setPosition(Position.S).setName('Antoine Brooks Jr.').setTeam(Team.PIT).setAge(21).setSchool('Maryland').build(),
    Player.newBuilder().setPosition(Position.S).setName('Antoine Winfield Jr.').setTeam(Team.TAM).setAge(22).setSchool('Minnesota').build(),
    Player.newBuilder().setPosition(Position.S).setName('Ashtyn Davis').setTeam(Team.NYJ).setAge(23).setSchool('California').build(),
    Player.newBuilder().setPosition(Position.S).setName('Brandon Jones').setTeam(Team.MIA).setAge(22).setSchool('Texas').build(),
    Player.newBuilder().setPosition(Position.S).setName('Brian Cole II').setTeam(Team.MIN).setAge(23).setSchool('Mississippi St.').build(),
    Player.newBuilder().setPosition(Position.S).setName('Chris Jackson').setTeam(Team.TEN).setAge(22).setSchool('Marshall').build(),
    Player.newBuilder().setPosition(Position.S).setName('Daniel Thomas').setTeam(Team.JAX).setAge(22).setSchool('Auburn').build(),
    Player.newBuilder().setPosition(Position.S).setName('Geno Stone').setTeam(Team.BAL).setAge(21).setSchool('Iowa').build(),
    Player.newBuilder().setPosition(Position.S).setName('Grant Delpit').setTeam(Team.CLE).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.S).setName('Jaylinn Hawkins').setTeam(Team.ATL).setAge(23).setSchool('California').build(),
    Player.newBuilder().setPosition(Position.S).setName('Jeremy Chinn').setTeam(Team.CAR).setAge(22).setSchool('Southern Illinois').build(),
    Player.newBuilder().setPosition(Position.S).setName('Jordan Fuller').setTeam(Team.LAR).setAge(22).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.S).setName('Josh Metellus').setTeam(Team.MIN).setAge(22).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.S).setName('Julian Blackmon').setTeam(Team.IND).setAge(22).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.S).setName("K'Von Wallace").setTeam(Team.PHI).setAge(23).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.S).setName('Kamren Curl').setTeam(Team.WAS).setAge(21).setSchool('Arkansas').build(),
    Player.newBuilder().setPosition(Position.S).setName('Kenny Robinson Jr.').setTeam(Team.CAR).setAge(21).setSchool('West Virginia').build(),
    Player.newBuilder().setPosition(Position.S).setName('Kyle Dugger').setTeam(Team.NWE).setAge(24).setSchool('').build(),
    Player.newBuilder().setPosition(Position.S).setName("L'Jarius Sneed").setTeam(Team.KAN).setAge(23).setSchool('Louisiana Tech').build(),
    Player.newBuilder().setPosition(Position.S).setName('Tanner Muse').setTeam(Team.LVR).setAge(24).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.S).setName('Terrell Burgess').setTeam(Team.LAR).setAge(21).setSchool('Utah').build(),
    Player.newBuilder().setPosition(Position.S).setName('Vernon Scott').setTeam(Team.GNB).setAge(22).setSchool('TCU').build(),
    Player.newBuilder().setPosition(Position.S).setName('Xavier McKinney').setTeam(Team.NYG).setAge(21).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.T).setName('Andrew Thomas').setTeam(Team.NYG).setAge(21).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.T).setName('Arlington Hambright').setTeam(Team.CHI).setAge(24).setSchool('Colorado').build(),
    Player.newBuilder().setPosition(Position.T).setName('Austin Jackson').setTeam(Team.MIA).setAge(21).setSchool('USC').build(),
    Player.newBuilder().setPosition(Position.T).setName('Blake Brandel').setTeam(Team.MIN).setAge(23).setSchool('Oregon St.').build(),
    Player.newBuilder().setPosition(Position.T).setName('Cameron Clark').setTeam(Team.NYJ).setAge(22).setSchool('Charlotte').build(),
    Player.newBuilder().setPosition(Position.T).setName('Charlie Heck').setTeam(Team.HOU).setAge(23).setSchool('North Carolina').build(),
    Player.newBuilder().setPosition(Position.T).setName('Colton McKivitz').setTeam(Team.SFO).setAge(24).setSchool('West Virginia').build(),
    Player.newBuilder().setPosition(Position.T).setName('Ezra Cleveland').setTeam(Team.MIN).setAge(22).setSchool('Boise St.').build(),
    Player.newBuilder().setPosition(Position.T).setName('Hakeem Adeniji').setTeam(Team.CIN).setAge(22).setSchool('Kansas').build(),
    Player.newBuilder().setPosition(Position.T).setName('Isaiah Wilson').setTeam(Team.TEN).setAge(21).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.T).setName('Jedrick Wills Jr.').setTeam(Team.CLE).setAge(21).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.T).setName('Jon Runyan').setTeam(Team.GNB).setAge(23).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.T).setName('Josh Jones').setTeam(Team.ARI).setAge(23).setSchool('Houston').build(),
    Player.newBuilder().setPosition(Position.T).setName('Justin Herron').setTeam(Team.NWE).setAge(24).setSchool('Wake Forest').build(),
    Player.newBuilder().setPosition(Position.T).setName('Lucas Niang').setTeam(Team.KAN).setAge(22).setSchool('TCU').build(),
    Player.newBuilder().setPosition(Position.T).setName('Matt Peart').setTeam(Team.NYG).setAge(23).setSchool('Connecticut').build(),
    Player.newBuilder().setPosition(Position.T).setName('Mekhi Becton').setTeam(Team.NYJ).setAge(21).setSchool('Louisville').build(),
    Player.newBuilder().setPosition(Position.T).setName('Prince Tega Wanogho').setTeam(Team.PHI).setAge(22).setSchool('Auburn').build(),
    Player.newBuilder().setPosition(Position.T).setName('Saahdiq Charles').setTeam(Team.WAS).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.T).setName('Simon Stepaniak').setTeam(Team.GNB).setAge(23).setSchool('Indiana').build(),
    Player.newBuilder().setPosition(Position.T).setName('Tristan Wirfs').setTeam(Team.TAM).setAge(21).setSchool('Iowa').build(),
    Player.newBuilder().setPosition(Position.T).setName('Tyre Phillips').setTeam(Team.BAL).setAge(23).setSchool('Mississippi St.').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Adam Trautman').setTeam(Team.NOR).setAge(23).setSchool('1').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Albert Okwuegbunam').setTeam(Team.DEN).setAge(22).setSchool('Missouri').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Brycen Hopkins').setTeam(Team.LAR).setAge(23).setSchool('Purdue').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Charlie Woerner').setTeam(Team.SFO).setAge(22).setSchool('Georgia').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Colby Parkinson').setTeam(Team.SEA).setAge(21).setSchool('Stanford').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Cole Kmet').setTeam(Team.CHI).setAge(21).setSchool('Notre Dame').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Dalton Keene').setTeam(Team.NWE).setAge(21).setSchool('Virginia Tech').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Devin Asiasi').setTeam(Team.NWE).setAge(23).setSchool('UCLA').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Harrison Bryant').setTeam(Team.CLE).setAge(22).setSchool('Florida Atlantic').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Josiah Deguara').setTeam(Team.GNB).setAge(23).setSchool('Cincinnati').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Stephen Sullivan').setTeam(Team.SEA).setAge(23).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.TE).setName('Tyler Davis').setTeam(Team.JAX).setAge(23).setSchool('Georgia Tech').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Antonio Gandy-Golden').setTeam(Team.WAS).setAge(22).setSchool('Liberty').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Brandon Aiyuk').setTeam(Team.SFO).setAge(22).setSchool('Arizona St.').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Bryan Edwards').setTeam(Team.LVR).setAge(21).setSchool('South Carolina').build(),
    Player.newBuilder().setPosition(Position.WR).setName('CeeDee Lamb').setTeam(Team.DAL).setAge(21).setSchool('Oklahoma').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Chase Claypool').setTeam(Team.PIT).setAge(22).setSchool('Notre Dame').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Collin Johnson').setTeam(Team.JAX).setAge(22).setSchool('Texas').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Darnell Mooney').setTeam(Team.CHI).setAge(22).setSchool('Tulane').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Denzel Mims').setTeam(Team.NYJ).setAge(22).setSchool('Baylor').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Devin Duvernay').setTeam(Team.BAL).setAge(22).setSchool('Texas').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Dezmon Patmon').setTeam(Team.IND).setAge(22).setSchool('Washington St.').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Donovan Peoples-Jones').setTeam(Team.CLE).setAge(21).setSchool('Michigan').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Freddie Swain').setTeam(Team.SEA).setAge(22).setSchool('Florida').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Gabriel Davis').setTeam(Team.BUF).setAge(21).setSchool('Central Florida').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Henry Ruggs III').setTeam(Team.LVR).setAge(21).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Isaiah Coulter').setTeam(Team.HOU).setAge(21).setSchool('').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Isaiah Hodgins').setTeam(Team.BUF).setAge(21).setSchool('Oregon St.').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Jalen Reagor').setTeam(Team.PHI).setAge(21).setSchool('TCU').build(),
    Player.newBuilder().setPosition(Position.WR).setName('James Proche').setTeam(Team.BAL).setAge(23).setSchool('SMU').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Jauan Jennings').setTeam(Team.SFO).setAge(23).setSchool('Tennessee').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Jerry Jeudy').setTeam(Team.DEN).setAge(21).setSchool('Alabama').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Joe Reed').setTeam(Team.LAC).setAge(22).setSchool('Virginia').build(),
    Player.newBuilder().setPosition(Position.WR).setName('John Hightower').setTeam(Team.PHI).setAge(24).setSchool('Boise St.').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Justin Jefferson').setTeam(Team.MIN).setAge(21).setSchool('LSU').build(),
    Player.newBuilder().setPosition(Position.WR).setName('K.J. Hill').setTeam(Team.LAC).setAge(22).setSchool('Ohio St.').build(),
    Player.newBuilder().setPosition(Position.WR).setName('K.J. Osborn').setTeam(Team.MIN).setAge(23).setSchool('Miami (FL)').build(),
    Player.newBuilder().setPosition(Position.WR).setName('KJ Hamler').setTeam(Team.DEN).setAge(21).setSchool('Penn St.').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Laviska Shenault Jr.').setTeam(Team.JAX).setAge(21).setSchool('Colorado').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Lynn Bowden Jr.').setTeam(Team.LVR).setAge(22).setSchool('Kentucky').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Michael Pittman Jr.').setTeam(Team.IND).setAge(22).setSchool('USC').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Quez Watkins').setTeam(Team.PHI).setAge(22).setSchool('Southern Miss').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Quintez Cephus').setTeam(Team.DET).setAge(22).setSchool('Wisconsin').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Tee Higgins').setTeam(Team.CIN).setAge(21).setSchool('Clemson').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Tyler Johnson').setTeam(Team.TAM).setAge(22).setSchool('Minnesota').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Tyrie Cleveland').setTeam(Team.DEN).setAge(22).setSchool('Florida').build(),
    Player.newBuilder().setPosition(Position.WR).setName('Van Jefferson').setTeam(Team.LAR).setAge(24).setSchool('Mississippi').build(),
];
